// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeNonSerializedTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type AuthCliCodePost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/cli_auth_controller.ts').default['createCode'], false>
}
type AuthCliPollGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/cli_auth_controller.ts').default['poll'], false>
}
type AuthCliAuthorizePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/cli_auth.ts')['cliAuthorizeValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/cli_auth_controller.ts').default['authorize'], true>
}
type AuthRegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['registerValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['register'], true>
}
type AuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['loginValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['login'], true>
}
type AuthLogoutPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['logout'], false>
}
type AuthMeGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['me'], false>
}
type AuthMePatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['updateProfileValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['updateMe'], true>
}
type AuthGoogleUrlGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['googleAuthUrl'], false>
}
type AuthGoogleCallbackPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['googleCallbackValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/auth_controller.ts').default['googleCallback'], true>
}
type EmbedBootstrapPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/embed.ts')['embedBootstrapValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/embeds_controller.ts').default['bootstrap'], true>
}
type InvitesIdPreviewGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/organization_invites_controller.ts').default['preview'], false>
}
type SharesIdGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/document_shares_controller.ts').default['resolvePublic'], false>
}
type WorkspacesGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/workspaces_controller.ts').default['index'], false>
}
type WorkspacesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/workspace.ts')['createWorkspaceValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/workspaces_controller.ts').default['store'], true>
}
type MeOrganizationsGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/organizations_controller.ts').default['index'], false>
}
type InvitesAcceptPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/organization_invite.ts')['acceptOrganizationInviteValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/organization_invites_controller.ts').default['accept'], true>
}
type AgentInvocationsIdGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/agent_invocations_controller.ts').default['show'], false>
}
type AgentInvocationsIdCommandPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/agent_invocation.ts')['CommandSchema']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/agent_invocations_controller.ts').default['command'], true>
}
type AgentInvocationsIdQuestionsIdAnswerPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/agent_invocation.ts')['answerQuestionValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/agent_invocations_controller.ts').default['answerQuestion'], true>
}
type WorkspacesIdGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/workspaces_controller.ts').default['show'], false>
}
type WorkspacesIdDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/workspaces_controller.ts').default['destroy'], false>
}
type WorkspacesIdPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/workspace.ts')['updateWorkspaceValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/workspaces_controller.ts').default['update'], true>
}
type WorkspacesIdDuplicatePost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/workspaces_controller.ts').default['duplicate'], false>
}
type WorkspacesIdOrganizationGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/organizations_controller.ts').default['showCurrent'], false>
}
type WorkspacesIdOnboardingStartPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/agent_invocations_controller.ts').default['startOnboarding'], false>
}
type WorkspacesIdAgentInvokePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/agent_invocation.ts')['invokeValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/agent_invocations_controller.ts').default['invoke'], true>
}
type WorkspacesIdTasksGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/task.ts')['tasksIndexQueryValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/tasks_controller.ts').default['index'], true>
}
type WorkspacesIdTasksIdArchivePost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/tasks_controller.ts').default['archive'], false>
}
type WorkspacesIdSuggestedtasksGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/workspace_suggested_tasks_controller.ts').default['index'], false>
}
type WorkspacesIdSuggestedtasksIdDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/workspace_suggested_tasks_controller.ts').default['destroy'], false>
}
type WorkspacesIdConnectionsGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/connections_controller.ts').default['index'], false>
}
type WorkspacesIdConnectionsToolkitsGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/connections_controller.ts').default['toolkits'], false>
}
type WorkspacesIdConnectionsCustomauthrequirementsGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/connections_controller.ts').default['customAuthRequirements'], false>
}
type WorkspacesIdMarvinconfigGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/marvin_config_controller.ts').default['show'], false>
}
type WorkspacesIdMarvinconfigPatch = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/marvin_config_controller.ts').default['update'], false>
}
type WorkspacesIdDebugSandboxstatusGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/debug_bash_controller.ts').default['status'], false>
}
type WorkspacesIdDebugBashPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/debug_bash_controller.ts').default['execute'], false>
}
type WorkspacesIdDebugShutdownPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/debug_bash_controller.ts').default['shutdown'], false>
}
type LinkMetadataPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/link_metadata.ts')['linkMetadataValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/link_metadata_controller.ts').default['fetch'], true>
}
type WorkspacesIdSlackMessagePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/slack_message.ts')['fetchSlackMessageValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/slack_message_controller.ts').default['fetch'], true>
}
type WorkspacesIdConnectionsInitiatePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/connection.ts')['initiateConnectionValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/connections_controller.ts').default['initiate'], true>
}
type WorkspacesIdConnectionsIdDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/connections_controller.ts').default['destroy'], false>
}
type WorkspacesIdNodesIdSummarizePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/node_summary.ts')['summarizeNodeValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/node_summary_controller.ts').default['summarize'], true>
}
type WorkspacesIdDocumentsharesGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/document_shares_controller.ts').default['index'], false>
}
type WorkspacesIdNotesIdShareGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/document_shares_controller.ts').default['show'], false>
}
type WorkspacesIdNotesIdSharePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/document_share.ts')['createDocumentShareValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/document_shares_controller.ts').default['store'], true>
}
type WorkspacesIdNotesIdSharePatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/document_share.ts')['updateDocumentShareValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/document_shares_controller.ts').default['update'], true>
}
type WorkspacesIdNotesIdShareDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/document_shares_controller.ts').default['destroy'], false>
}
type WorkspacesIdOrganizationPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/organization.ts')['updateOrganizationValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/organizations_controller.ts').default['update'], true>
}
type WorkspacesIdMembersIdRolePatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/organization_member.ts')['updateOrganizationMemberRoleValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/organization_members_controller.ts').default['updateRole'], true>
}
type WorkspacesIdMembersIdDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/organization_members_controller.ts').default['destroy'], false>
}
type WorkspacesIdInvitesGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/organization_invites_controller.ts').default['index'], false>
}
type WorkspacesIdInvitesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/organization_invite.ts')['createOrganizationInviteValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/organization_invites_controller.ts').default['store'], true>
}
type WorkspacesIdInvitesIdRevokePost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/organization_invites_controller.ts').default['revoke'], false>
}
type UserConfigGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/user_config_controller.ts').default['show'], false>
}
type UserConfigPatch = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/user_config_controller.ts').default['update'], false>
}
type SkillsGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/skills_controller.ts').default['index'], false>
}
type SkillsStatsGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/skills_controller.ts').default['stats'], false>
}
type SkillsIdGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/skills_controller.ts').default['show'], false>
}
type SkillsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/skill.ts')['createSkillValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/skills_controller.ts').default['store'], true>
}
type SkillsIdPut = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/skill.ts')['updateSkillValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/skills_controller.ts').default['update'], true>
}
type SkillsIdDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/skills_controller.ts').default['destroy'], false>
}
type SkillsIdEnablePut = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/skills_controller.ts').default['enable'], false>
}
type SkillsIdDisablePut = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/skills_controller.ts').default['disable'], false>
}
type SkillsIdDuplicatePost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/skills_controller.ts').default['duplicate'], false>
}
type TranscribePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/transcribe.ts')['transcribeValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/transcribe_controller.ts').default['transcribe'], true>
}
type WorkspacesIdMembersGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/organization_members_controller.ts').default['index'], false>
}
type FilesSignedurlGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/files_controller.ts').default['getSignedUrl'], false>
}
type WorkspacesIdFilesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/file_upload.ts')['fileUploadValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/files_controller.ts').default['upload'], true>
}
type WorkspacesIdYjssockettokenPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/yjs_socket_tokens_controller.ts').default['store'], false>
}
type SharesIdSocketaccessGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/document_shares_controller.ts').default['resolveSocketAccess'], false>
}
type WorkspacesIdDocumentUpdatedPost = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/workspace_documents_controller.ts').default['notifyDocumentUpdated'], false>
}
type WaitlistPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/waitlist.ts')['waitlistValidator']>>
  response: MakeNonSerializedTuyauResponse<import('../app/controllers/waitlist_controller.ts').default['store'], true>
}
export interface ApiDefinition {
  'auth': {
    'cli': {
      'code': {
        '$url': {
        };
        '$post': AuthCliCodePost;
      };
      'poll': {
        '$url': {
        };
        '$get': AuthCliPollGetHead;
        '$head': AuthCliPollGetHead;
      };
      'authorize': {
        '$url': {
        };
        '$post': AuthCliAuthorizePost;
      };
    };
    'register': {
      '$url': {
      };
      '$post': AuthRegisterPost;
    };
    'login': {
      '$url': {
      };
      '$post': AuthLoginPost;
    };
    'logout': {
      '$url': {
      };
      '$post': AuthLogoutPost;
    };
    'me': {
      '$url': {
      };
      '$get': AuthMeGetHead;
      '$head': AuthMeGetHead;
      '$patch': AuthMePatch;
    };
    'google': {
      'url': {
        '$url': {
        };
        '$get': AuthGoogleUrlGetHead;
        '$head': AuthGoogleUrlGetHead;
      };
      'callback': {
        '$url': {
        };
        '$post': AuthGoogleCallbackPost;
      };
    };
  };
  'embed': {
    'bootstrap': {
      '$url': {
      };
      '$post': EmbedBootstrapPost;
    };
  };
  'invites': {
    ':token': {
      'preview': {
        '$url': {
        };
        '$get': InvitesIdPreviewGetHead;
        '$head': InvitesIdPreviewGetHead;
      };
    };
    'accept': {
      '$url': {
      };
      '$post': InvitesAcceptPost;
    };
  };
  'shares': {
    ':longHashId': {
      '$url': {
      };
      '$get': SharesIdGetHead;
      '$head': SharesIdGetHead;
      'socket-access': {
        '$url': {
        };
        '$get': SharesIdSocketaccessGetHead;
        '$head': SharesIdSocketaccessGetHead;
      };
    };
  };
  'workspaces': {
    '$url': {
    };
    '$get': WorkspacesGetHead;
    '$head': WorkspacesGetHead;
    '$post': WorkspacesPost;
    ':id': {
      '$url': {
      };
      '$get': WorkspacesIdGetHead;
      '$head': WorkspacesIdGetHead;
      '$delete': WorkspacesIdDelete;
      '$patch': WorkspacesIdPatch;
      'duplicate': {
        '$url': {
        };
        '$post': WorkspacesIdDuplicatePost;
      };
      'organization': {
        '$url': {
        };
        '$get': WorkspacesIdOrganizationGetHead;
        '$head': WorkspacesIdOrganizationGetHead;
        '$patch': WorkspacesIdOrganizationPatch;
      };
      'onboarding': {
        'start': {
          '$url': {
          };
          '$post': WorkspacesIdOnboardingStartPost;
        };
      };
      'agent': {
        'invoke': {
          '$url': {
          };
          '$post': WorkspacesIdAgentInvokePost;
        };
      };
      'tasks': {
        '$url': {
        };
        '$get': WorkspacesIdTasksGetHead;
        '$head': WorkspacesIdTasksGetHead;
        ':taskId': {
          'archive': {
            '$url': {
            };
            '$post': WorkspacesIdTasksIdArchivePost;
          };
        };
      };
      'suggested-tasks': {
        '$url': {
        };
        '$get': WorkspacesIdSuggestedtasksGetHead;
        '$head': WorkspacesIdSuggestedtasksGetHead;
        ':suggestionId': {
          '$url': {
          };
          '$delete': WorkspacesIdSuggestedtasksIdDelete;
        };
      };
      'connections': {
        '$url': {
        };
        '$get': WorkspacesIdConnectionsGetHead;
        '$head': WorkspacesIdConnectionsGetHead;
        'toolkits': {
          '$url': {
          };
          '$get': WorkspacesIdConnectionsToolkitsGetHead;
          '$head': WorkspacesIdConnectionsToolkitsGetHead;
        };
        'custom-auth-requirements': {
          '$url': {
          };
          '$get': WorkspacesIdConnectionsCustomauthrequirementsGetHead;
          '$head': WorkspacesIdConnectionsCustomauthrequirementsGetHead;
        };
        'initiate': {
          '$url': {
          };
          '$post': WorkspacesIdConnectionsInitiatePost;
        };
        ':connectionId': {
          '$url': {
          };
          '$delete': WorkspacesIdConnectionsIdDelete;
        };
      };
      'marvin-config': {
        '$url': {
        };
        '$get': WorkspacesIdMarvinconfigGetHead;
        '$head': WorkspacesIdMarvinconfigGetHead;
        '$patch': WorkspacesIdMarvinconfigPatch;
      };
      'debug': {
        'sandbox-status': {
          '$url': {
          };
          '$get': WorkspacesIdDebugSandboxstatusGetHead;
          '$head': WorkspacesIdDebugSandboxstatusGetHead;
        };
        'bash': {
          '$url': {
          };
          '$post': WorkspacesIdDebugBashPost;
        };
        'shutdown': {
          '$url': {
          };
          '$post': WorkspacesIdDebugShutdownPost;
        };
      };
      'slack': {
        'message': {
          '$url': {
          };
          '$post': WorkspacesIdSlackMessagePost;
        };
      };
      'nodes': {
        ':nodeId': {
          'summarize': {
            '$url': {
            };
            '$post': WorkspacesIdNodesIdSummarizePost;
          };
        };
      };
      'document-shares': {
        '$url': {
        };
        '$get': WorkspacesIdDocumentsharesGetHead;
        '$head': WorkspacesIdDocumentsharesGetHead;
      };
      'notes': {
        ':noteId': {
          'share': {
            '$url': {
            };
            '$get': WorkspacesIdNotesIdShareGetHead;
            '$head': WorkspacesIdNotesIdShareGetHead;
            '$post': WorkspacesIdNotesIdSharePost;
            '$patch': WorkspacesIdNotesIdSharePatch;
            '$delete': WorkspacesIdNotesIdShareDelete;
          };
        };
      };
      'members': {
        ':userId': {
          'role': {
            '$url': {
            };
            '$patch': WorkspacesIdMembersIdRolePatch;
          };
          '$url': {
          };
          '$delete': WorkspacesIdMembersIdDelete;
        };
        '$url': {
        };
        '$get': WorkspacesIdMembersGetHead;
        '$head': WorkspacesIdMembersGetHead;
      };
      'invites': {
        '$url': {
        };
        '$get': WorkspacesIdInvitesGetHead;
        '$head': WorkspacesIdInvitesGetHead;
        '$post': WorkspacesIdInvitesPost;
        ':inviteId': {
          'revoke': {
            '$url': {
            };
            '$post': WorkspacesIdInvitesIdRevokePost;
          };
        };
      };
      'files': {
        '$url': {
        };
        '$post': WorkspacesIdFilesPost;
      };
      'yjs-socket-token': {
        '$url': {
        };
        '$post': WorkspacesIdYjssockettokenPost;
      };
      'document': {
        'updated': {
          '$url': {
          };
          '$post': WorkspacesIdDocumentUpdatedPost;
        };
      };
    };
  };
  'me': {
    'organizations': {
      '$url': {
      };
      '$get': MeOrganizationsGetHead;
      '$head': MeOrganizationsGetHead;
    };
  };
  'agent': {
    'invocations': {
      ':invocationId': {
        '$url': {
        };
        '$get': AgentInvocationsIdGetHead;
        '$head': AgentInvocationsIdGetHead;
        'command': {
          '$url': {
          };
          '$post': AgentInvocationsIdCommandPost;
        };
        'questions': {
          ':itemId': {
            'answer': {
              '$url': {
              };
              '$post': AgentInvocationsIdQuestionsIdAnswerPost;
            };
          };
        };
      };
    };
  };
  'link-metadata': {
    '$url': {
    };
    '$post': LinkMetadataPost;
  };
  'user-config': {
    '$url': {
    };
    '$get': UserConfigGetHead;
    '$head': UserConfigGetHead;
    '$patch': UserConfigPatch;
  };
  'skills': {
    '$url': {
    };
    '$get': SkillsGetHead;
    '$head': SkillsGetHead;
    'stats': {
      '$url': {
      };
      '$get': SkillsStatsGetHead;
      '$head': SkillsStatsGetHead;
    };
    ':id': {
      '$url': {
      };
      '$get': SkillsIdGetHead;
      '$head': SkillsIdGetHead;
      '$put': SkillsIdPut;
      '$delete': SkillsIdDelete;
      'enable': {
        '$url': {
        };
        '$put': SkillsIdEnablePut;
      };
      'disable': {
        '$url': {
        };
        '$put': SkillsIdDisablePut;
      };
      'duplicate': {
        '$url': {
        };
        '$post': SkillsIdDuplicatePost;
      };
    };
    '$post': SkillsPost;
  };
  'transcribe': {
    '$url': {
    };
    '$post': TranscribePost;
  };
  'files': {
    'signed-url': {
      '$url': {
      };
      '$get': FilesSignedurlGetHead;
      '$head': FilesSignedurlGetHead;
    };
  };
  'waitlist': {
    '$url': {
    };
    '$post': WaitlistPost;
  };
}
const routes = [
  {
    params: ["*"],
    name: 'drive.fs.serve',
    path: '/file/*',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'cli.code',
    path: '/auth/cli/code',
    method: ["POST"],
    types: {} as AuthCliCodePost,
  },
  {
    params: [],
    name: 'cli.poll',
    path: '/auth/cli/poll',
    method: ["GET","HEAD"],
    types: {} as AuthCliPollGetHead,
  },
  {
    params: [],
    name: 'cli.authorize',
    path: '/auth/cli/authorize',
    method: ["POST"],
    types: {} as AuthCliAuthorizePost,
  },
  {
    params: [],
    name: 'register',
    path: '/auth/register',
    method: ["POST"],
    types: {} as AuthRegisterPost,
  },
  {
    params: [],
    name: 'login',
    path: '/auth/login',
    method: ["POST"],
    types: {} as AuthLoginPost,
  },
  {
    params: [],
    name: 'logout',
    path: '/auth/logout',
    method: ["POST"],
    types: {} as AuthLogoutPost,
  },
  {
    params: [],
    name: 'me',
    path: '/auth/me',
    method: ["GET","HEAD"],
    types: {} as AuthMeGetHead,
  },
  {
    params: [],
    name: 'me.update',
    path: '/auth/me',
    method: ["PATCH"],
    types: {} as AuthMePatch,
  },
  {
    params: [],
    name: 'google.url',
    path: '/auth/google/url',
    method: ["GET","HEAD"],
    types: {} as AuthGoogleUrlGetHead,
  },
  {
    params: [],
    name: 'google.callback',
    path: '/auth/google/callback',
    method: ["POST"],
    types: {} as AuthGoogleCallbackPost,
  },
  {
    params: [],
    name: 'embed.bootstrap',
    path: '/embed/bootstrap',
    method: ["POST"],
    types: {} as EmbedBootstrapPost,
  },
  {
    params: ["token"],
    name: 'organizationInvites.preview',
    path: '/invites/:token/preview',
    method: ["GET","HEAD"],
    types: {} as InvitesIdPreviewGetHead,
  },
  {
    params: ["longHashId"],
    name: 'documentShares.resolvePublic',
    path: '/shares/:longHashId',
    method: ["GET","HEAD"],
    types: {} as SharesIdGetHead,
  },
  {
    params: [],
    name: 'workspaces.index',
    path: '/workspaces',
    method: ["GET","HEAD"],
    types: {} as WorkspacesGetHead,
  },
  {
    params: [],
    name: 'workspaces.store',
    path: '/workspaces',
    method: ["POST"],
    types: {} as WorkspacesPost,
  },
  {
    params: [],
    name: 'organizations.index',
    path: '/me/organizations',
    method: ["GET","HEAD"],
    types: {} as MeOrganizationsGetHead,
  },
  {
    params: [],
    name: 'organizationInvites.accept',
    path: '/invites/accept',
    method: ["POST"],
    types: {} as InvitesAcceptPost,
  },
  {
    params: ["invocationId"],
    name: 'agent.show',
    path: '/agent/invocations/:invocationId',
    method: ["GET","HEAD"],
    types: {} as AgentInvocationsIdGetHead,
  },
  {
    params: ["invocationId"],
    name: 'agent.command',
    path: '/agent/invocations/:invocationId/command',
    method: ["POST"],
    types: {} as AgentInvocationsIdCommandPost,
  },
  {
    params: ["invocationId","itemId"],
    name: 'agent.questions.answer',
    path: '/agent/invocations/:invocationId/questions/:itemId/answer',
    method: ["POST"],
    types: {} as AgentInvocationsIdQuestionsIdAnswerPost,
  },
  {
    params: ["id"],
    name: 'workspaces.show',
    path: '/workspaces/:id',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdGetHead,
  },
  {
    params: ["id"],
    name: 'workspaces.destroy',
    path: '/workspaces/:id',
    method: ["DELETE"],
    types: {} as WorkspacesIdDelete,
  },
  {
    params: ["id"],
    name: 'workspaces.update',
    path: '/workspaces/:id',
    method: ["PATCH"],
    types: {} as WorkspacesIdPatch,
  },
  {
    params: ["id"],
    name: 'workspaces.duplicate',
    path: '/workspaces/:id/duplicate',
    method: ["POST"],
    types: {} as WorkspacesIdDuplicatePost,
  },
  {
    params: ["id"],
    name: 'organizations.show',
    path: '/workspaces/:id/organization',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdOrganizationGetHead,
  },
  {
    params: ["id"],
    name: 'workspaces.onboarding.start',
    path: '/workspaces/:id/onboarding/start',
    method: ["POST"],
    types: {} as WorkspacesIdOnboardingStartPost,
  },
  {
    params: ["id"],
    name: 'agent.invoke',
    path: '/workspaces/:id/agent/invoke',
    method: ["POST"],
    types: {} as WorkspacesIdAgentInvokePost,
  },
  {
    params: ["id"],
    name: 'tasks.index',
    path: '/workspaces/:id/tasks',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdTasksGetHead,
  },
  {
    params: ["id","taskId"],
    name: 'tasks.archive',
    path: '/workspaces/:id/tasks/:taskId/archive',
    method: ["POST"],
    types: {} as WorkspacesIdTasksIdArchivePost,
  },
  {
    params: ["id"],
    name: 'workspaceSuggestedTasks.index',
    path: '/workspaces/:id/suggested-tasks',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdSuggestedtasksGetHead,
  },
  {
    params: ["id","suggestionId"],
    name: 'workspaceSuggestedTasks.destroy',
    path: '/workspaces/:id/suggested-tasks/:suggestionId',
    method: ["DELETE"],
    types: {} as WorkspacesIdSuggestedtasksIdDelete,
  },
  {
    params: ["id"],
    name: 'connections.index',
    path: '/workspaces/:id/connections',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdConnectionsGetHead,
  },
  {
    params: ["id"],
    name: 'connections.toolkits',
    path: '/workspaces/:id/connections/toolkits',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdConnectionsToolkitsGetHead,
  },
  {
    params: ["id"],
    name: 'connections.customAuthRequirements',
    path: '/workspaces/:id/connections/custom-auth-requirements',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdConnectionsCustomauthrequirementsGetHead,
  },
  {
    params: ["id"],
    name: 'marvin.show',
    path: '/workspaces/:id/marvin-config',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdMarvinconfigGetHead,
  },
  {
    params: ["id"],
    name: 'marvin.update',
    path: '/workspaces/:id/marvin-config',
    method: ["PATCH"],
    types: {} as WorkspacesIdMarvinconfigPatch,
  },
  {
    params: ["id"],
    name: 'debug.sandbox.status',
    path: '/workspaces/:id/debug/sandbox-status',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdDebugSandboxstatusGetHead,
  },
  {
    params: ["id"],
    name: 'debug.bash',
    path: '/workspaces/:id/debug/bash',
    method: ["POST"],
    types: {} as WorkspacesIdDebugBashPost,
  },
  {
    params: ["id"],
    name: 'debug.sandbox.shutdown',
    path: '/workspaces/:id/debug/shutdown',
    method: ["POST"],
    types: {} as WorkspacesIdDebugShutdownPost,
  },
  {
    params: [],
    name: 'link.metadata',
    path: '/link-metadata',
    method: ["POST"],
    types: {} as LinkMetadataPost,
  },
  {
    params: ["id"],
    name: 'slack.message.fetch',
    path: '/workspaces/:id/slack/message',
    method: ["POST"],
    types: {} as WorkspacesIdSlackMessagePost,
  },
  {
    params: ["id"],
    name: 'connections.initiate',
    path: '/workspaces/:id/connections/initiate',
    method: ["POST"],
    types: {} as WorkspacesIdConnectionsInitiatePost,
  },
  {
    params: ["id","connectionId"],
    name: 'connections.destroy',
    path: '/workspaces/:id/connections/:connectionId',
    method: ["DELETE"],
    types: {} as WorkspacesIdConnectionsIdDelete,
  },
  {
    params: ["id","nodeId"],
    name: 'nodes.summarize',
    path: '/workspaces/:id/nodes/:nodeId/summarize',
    method: ["POST"],
    types: {} as WorkspacesIdNodesIdSummarizePost,
  },
  {
    params: ["id"],
    name: 'documentShares.index',
    path: '/workspaces/:id/document-shares',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdDocumentsharesGetHead,
  },
  {
    params: ["id","noteId"],
    name: 'documentShares.show',
    path: '/workspaces/:id/notes/:noteId/share',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdNotesIdShareGetHead,
  },
  {
    params: ["id","noteId"],
    name: 'documentShares.store',
    path: '/workspaces/:id/notes/:noteId/share',
    method: ["POST"],
    types: {} as WorkspacesIdNotesIdSharePost,
  },
  {
    params: ["id","noteId"],
    name: 'documentShares.update',
    path: '/workspaces/:id/notes/:noteId/share',
    method: ["PATCH"],
    types: {} as WorkspacesIdNotesIdSharePatch,
  },
  {
    params: ["id","noteId"],
    name: 'documentShares.destroy',
    path: '/workspaces/:id/notes/:noteId/share',
    method: ["DELETE"],
    types: {} as WorkspacesIdNotesIdShareDelete,
  },
  {
    params: ["id"],
    name: 'organizations.update',
    path: '/workspaces/:id/organization',
    method: ["PATCH"],
    types: {} as WorkspacesIdOrganizationPatch,
  },
  {
    params: ["id","userId"],
    name: 'organizationMembers.updateRole',
    path: '/workspaces/:id/members/:userId/role',
    method: ["PATCH"],
    types: {} as WorkspacesIdMembersIdRolePatch,
  },
  {
    params: ["id","userId"],
    name: 'organizationMembers.destroy',
    path: '/workspaces/:id/members/:userId',
    method: ["DELETE"],
    types: {} as WorkspacesIdMembersIdDelete,
  },
  {
    params: ["id"],
    name: 'organizationInvites.index',
    path: '/workspaces/:id/invites',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdInvitesGetHead,
  },
  {
    params: ["id"],
    name: 'organizationInvites.store',
    path: '/workspaces/:id/invites',
    method: ["POST"],
    types: {} as WorkspacesIdInvitesPost,
  },
  {
    params: ["id","inviteId"],
    name: 'organizationInvites.revoke',
    path: '/workspaces/:id/invites/:inviteId/revoke',
    method: ["POST"],
    types: {} as WorkspacesIdInvitesIdRevokePost,
  },
  {
    params: [],
    name: 'userConfig.show',
    path: '/user-config',
    method: ["GET","HEAD"],
    types: {} as UserConfigGetHead,
  },
  {
    params: [],
    name: 'userConfig.update',
    path: '/user-config',
    method: ["PATCH"],
    types: {} as UserConfigPatch,
  },
  {
    params: [],
    name: 'skills.index',
    path: '/skills',
    method: ["GET","HEAD"],
    types: {} as SkillsGetHead,
  },
  {
    params: [],
    name: 'skills.stats',
    path: '/skills/stats',
    method: ["GET","HEAD"],
    types: {} as SkillsStatsGetHead,
  },
  {
    params: ["id"],
    name: 'skills.show',
    path: '/skills/:id',
    method: ["GET","HEAD"],
    types: {} as SkillsIdGetHead,
  },
  {
    params: [],
    name: 'skills.store',
    path: '/skills',
    method: ["POST"],
    types: {} as SkillsPost,
  },
  {
    params: ["id"],
    name: 'skills.update',
    path: '/skills/:id',
    method: ["PUT"],
    types: {} as SkillsIdPut,
  },
  {
    params: ["id"],
    name: 'skills.destroy',
    path: '/skills/:id',
    method: ["DELETE"],
    types: {} as SkillsIdDelete,
  },
  {
    params: ["id"],
    name: 'skills.enable',
    path: '/skills/:id/enable',
    method: ["PUT"],
    types: {} as SkillsIdEnablePut,
  },
  {
    params: ["id"],
    name: 'skills.disable',
    path: '/skills/:id/disable',
    method: ["PUT"],
    types: {} as SkillsIdDisablePut,
  },
  {
    params: ["id"],
    name: 'skills.duplicate',
    path: '/skills/:id/duplicate',
    method: ["POST"],
    types: {} as SkillsIdDuplicatePost,
  },
  {
    params: [],
    name: 'transcribe',
    path: '/transcribe',
    method: ["POST"],
    types: {} as TranscribePost,
  },
  {
    params: ["id"],
    name: 'organizationMembers.index',
    path: '/workspaces/:id/members',
    method: ["GET","HEAD"],
    types: {} as WorkspacesIdMembersGetHead,
  },
  {
    params: [],
    name: 'files.signedUrl',
    path: '/files/signed-url',
    method: ["GET","HEAD"],
    types: {} as FilesSignedurlGetHead,
  },
  {
    params: ["id"],
    name: 'workspaces.files.upload',
    path: '/workspaces/:id/files',
    method: ["POST"],
    types: {} as WorkspacesIdFilesPost,
  },
  {
    params: ["id"],
    name: 'yjsSocketTokens.store',
    path: '/workspaces/:id/yjs-socket-token',
    method: ["POST"],
    types: {} as WorkspacesIdYjssockettokenPost,
  },
  {
    params: ["longHashId"],
    name: 'documentShares.resolveSocketAccess',
    path: '/shares/:longHashId/socket-access',
    method: ["GET","HEAD"],
    types: {} as SharesIdSocketaccessGetHead,
  },
  {
    params: [],
    name: 'health',
    path: '/health',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'waitlist.store',
    path: '/waitlist',
    method: ["POST"],
    types: {} as WaitlistPost,
  },
  {
    params: [],
    name: 'home',
    path: '/',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
