import { execSync } from 'child_process'
import { writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const TEST_EMAIL = 'playwright-test@example.com'
const TEST_PASSWORD = 'playwright-test-password-123'

export default async function globalSetup() {
  // Skip user creation for smoke-only test runs
  const args = process.argv.join(' ')
  if (args.includes('smoke.spec') && !args.includes('workspace.spec')) {
    console.log('\n⏭️  Skipping test user creation (smoke tests only)\n')
    return
  }

  console.log('\n🔧 Creating test user...')

  try {
    // Create test user via backend command
    execSync(`node ace test:create-user "${TEST_EMAIL}" "${TEST_PASSWORD}"`, {
      cwd: resolve(__dirname, '../../../backend'),
      stdio: 'inherit',
    })

    // Write credentials to .env.test for the tests to use
    const envContent = `# Auto-generated by global-setup.ts
TEST_EMAIL=${TEST_EMAIL}
TEST_PASSWORD=${TEST_PASSWORD}
`
    writeFileSync(resolve(__dirname, '../../.env.test'), envContent)

    console.log('✅ Test user created\n')
  } catch (error) {
    console.error('❌ Failed to create test user:', error)
    console.error('\n💡 Make sure the backend is running: cd backend && pnpm dev\n')
    throw error
  }
}
