export const tips = [
  "Start vague, get specific—I'll ask the right questions to figure out what you actually need.",
  'Create a /context canvas with your product overview, team roster, and brand voice—I read it on every task.',
  'Connect Slack, Linear, or Gmail and ask "prep me for my weekly sync"—I\'ll pull live data and draft talking points.',
  'Build your PRD here, then say "turn this into a prompt for Claude Code"—I\'ll output engineering-ready specs.',
  "Buildout complex context, come back tomorrow. It's ready—this becomes your living roadmap I can search and reference.",
  'After any research task, ask me to "save the key findings as context"—I\'ll create a note your future self can reuse.',
  'Drop a competitor\'s website and say "analyze this"—I\'ll extract positioning, features, and pricing into a structured note.',
  "Use this as your pre-meeting prep space: paste an agenda, I'll pull relevant context and surface what needs your attention.",
  "Create a /templates canvas with your PRD structure, status update format, or decision doc—I'll follow them on future tasks. Or any other template.",
  'Share your workspace with your team—it becomes a shared context layer that anyone can query.',
  'When a decision feels stuck, ask "what am I missing?"—I\'ll search your workspace and the web, then challenge your assumptions.',
  "Upload meeting recordings or voice memos—I'll transcribe and extract action items into your existing task notes.",
  "Treat each canvas as a project war room: drop screenshots, links, docs, and notes in one place. I'll see all of it.",
  'Before a stakeholder conversation, ask "what questions should I expect?"—I\'ll prep you based on the project context.',
  'Say "draft a one-pager from everything in this canvas"—I\'ll synthesize scattered notes into a coherent narrative.',
  "When scoping a feature, paste your eng team's technical constraints—I'll factor them into recommendations automatically.",
  'After shipping, ask me to "create a retro template from this project"—I\'ll capture what worked for next time.',
  'Come back to the same workspace tomorrow—your context compounds. The more you build here, the more useful I become.',
  "This is a workbench, not a chat log. Edit notes directly, reorganize canvases, delete what's stale. I adapt to what's here.",
]
